/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.grpc.demo;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;

public class CheckoutD2Client {
  private static final Logger logger = LoggerFactory.getLogger(CheckoutD2Client.class.getName());

  public static void main(String[] args) throws IOException, InterruptedException {
    CheckoutClientScaler app = new CheckoutClientScaler();
    app.run();
  }
}
